// Action Types
export const POST_JOB_REQUEST = "POST_JOB_REQUEST";
export const POST_JOB_SUCCESS = "POST_JOB_SUCCESS";
export const POST_JOB_FAILURE = "POST_JOB_FAILURE";
export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";
export const APPLY_JOBS_REQUEST = "APPLY_JOBS_REQUEST";
export const APPLY_JOBS_SUCCESS = "APPLY_JOBS_SUCCESS";
export const APPLY_JOBS_FAILURE = "APPLY_JOBS_FAILURE";
